#spring.datasource.url=jdbc:postgresql://google/reporting?cloudSqlInstance=geometric-timer-468018-t6:asia-south1:fos-dev&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.url=jdbc:postgresql://google/reporting?cloudSqlInstance=double-voice-470212-b2:asia-south2:pulseprod&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.username=postgres
spring.datasource.password=pu1se@PRD
spring.jackson.time-zone=Asia/Kolkata
# Optional settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# google cloud storage
spring.cloud.gcp.project-id=double-voice-470212-b2
#spring.cloud.gcp.project-id=geometric-timer-468018-t6
gcs.bucket.name=pulse-dev
#gcs.bucket.serviceAccount.filename=geometric-timer-468018-t6-3649aa1fd5c6.json
gcs.bucket.serviceAccount.filename=double-voice-470212-b2-3500619ef8aa.json
spring.cloud.gcp.sql.enabled=true
#spring.cloud.gcp.sql.instance-connection-name=geometric-timer-468018-t6:asia-south1:fos-dev
spring.cloud.gcp.sql.instance-connection-name=double-voice-470212-b2:asia-south2:pulseprod
spring.cloud.gcp.sql.database-name=postgres