package com.fos.reporting.domain;

import com.fos.reporting.domain.ProductStatus;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;
import lombok.Data;

import java.math.BigDecimal;

/**
 * Data Transfer Object for representing a product.
 * Used for creating, updating, and displaying product information.
 */
@Data
public class ProductDto {

    /**
     * The unique identifier for the product.
     * This is generated by the system and is read-only for clients.
     */
    private Long productId;

    /**
     * The official name of the product (e.g., "Diesel", "Petrol 95").
     */
    @NotBlank(message = "Product name cannot be blank")
    @Size(min = 2, max = 100)
    private String productName;

    /**
     * A brief description of the product.
     */
    @Size(max = 500)
    private String description;

    /**
     * The total storage capacity for this product in its designated tank.
     */
    @NotNull(message = "Tank capacity cannot be null")
    @Positive(message = "Tank capacity must be a positive number")
    private Integer tankCapacity;

    /**
     * The current selling price per unit for the product.
     */
    @NotNull(message = "Price cannot be null")
    @Positive(message = "Price must be a positive value")
    private BigDecimal price;

    private ProductStatus status;
}